### ISSUE TITLE
Not linking to math library correctly

### ISSUE THREAD

**Issue by tamtech** [Opendigitalradio/ka9q-fec#1]
The make file was not linking to the math library correctly.  When compiling a program using the library, compile would fail stating log and sqrt undefined.

I added -lm in the makefile line 104 so that it became:

```
# for Linux et al
libfec.so: $(LIBS)
    gcc -fPIC -shared -Xlinker -soname=$@ -o $@ -Wl,-whole-archive $^ -Wl,-no-whole-archive -lc -lm
```

and it works now.  Hopefully you can update the repository in case other people have the same problem.

Cheers,
Tom

(using ubuntu 14.04 64bit for reference)

**Comment by mpbraendli** [comment]
Hi Tom,

thanks for the hint !

Cheers
mpb
