### ISSUE TITLE
How To Compile

### ISSUE THREAD

**Issue by allegfede** [Opendigitalradio/ka9q-fec#5]
Sorry, for the noob question, but: How do I compile your software?

I cloned the Git repository with:
git clone https://github.com/Opendigitalradio/ka9q-fec.git

and get into the source folder with:
cd ka9q-fec

but now, what i have to do to compile it?

Thanks :D

**Comment by mpbraendli** [comment]
Hey,

yeah I should specify this a bit clearer. You can use the automake-based way described in the INSTALL file, or use cmake.

I'll write something into the readme.

mpb

**Comment by mpbraendli** [comment]
See 52067f27f33e9147b46d5b21793eaca1e803d3ff

**Comment by allegfede** [comment]
thanks, i also discovered the install script in the wiki of
opendigitalradio.org.

you are very kind.

On Fri, May 13, 2016 at 2:00 PM, Matthias P. Braendli <
notifications@github.com> wrote:

> See 52067f2
> https://github.com/Opendigitalradio/ka9q-fec/commit/52067f27f33e9147b46d5b21793eaca1e803d3ff
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Opendigitalradio/ka9q-fec/issues/5#issuecomment-219024304

## 

Open TV Architecture project: http://sourceforge.net/projects/otva/

Messagenet VOIP: 5338759

My blogs: http://altri-media.blogspot.com/
               http://subbaqquerie.blogspot.com/

YouTube Channel: AllegFede

VIMEO HD videos: http://www.vimeo.com/user1912745/videos
