### ISSUE TITLE
segmentation fault in encode_rs_char()

### ISSUE THREAD

**Issue by aozima** [Opendigitalradio/ka9q-fec#6]
trace to 

```
encode_rs_char()
{
    feedback = INDEX_OF[data[i] ^ parity[0]];
}
```

"data[i] ^ parity[0]" result is 0~255.

but 

```
#define INDEX_OF (rs->index_of)

init_rs_char()
{
    rs->index_of = (data_t *)malloc(sizeof(data_t)*(rs->nn+1));
}
```

when rs->nn < 255, INDEX_OF[n] will out of memory.

Who can give some help?

**Comment by mpbraendli** [comment]
Hi,

sorry I don't know the code well enough to answer your question. We are using KA9Q's reed solomon code in https://github.com/Opendigitalradio/ODR-DabMux/blob/next/src/ReedSolomon.cpp

Maybe this can help you.

Cheers
mpb

**Comment by aozima** [comment]
thanks, 
the question answer is:
if RS(255,223), the data[i] range is 0~255
if RS(15, 11), the data[i] range is 0~15.

so, we must ensure the input data is correct .
