### ISSUE TITLE
Request for release tag

### ISSUE THREAD

**Issue by paraenggu** [Opendigitalradio/ka9q-fec#7]
I'm creating a SPEC file for packaging ka9q-fec on CentOS 7. It would be helpful if you could create a release tag.

Many thanks!

**Comment by mpbraendli** [comment]
Sali Chrigu,
I've created a tag.

Cheers
mpb

**Comment by paraenggu** [comment]
Thank you!

in case you're interested, the Spec file and the related RPM installation instructions are located at [radiorabe/centos-rpm-libfec-odr](https://github.com/radiorabe/centos-rpm-libfec-odr)
